import {
  THEMES,
  TAGS,
  LOCATION_TAGS,
  ACTIVITY_TAGS,
  EVENT_TAGS,
} from '../constants';

type Theme = (typeof THEMES)[number];
type Tag = (typeof TAGS)[number];
type LocationTag = (typeof LOCATION_TAGS)[number];
type ActivityTag = (typeof ACTIVITY_TAGS)[number];
type EventTag = (typeof EVENT_TAGS)[number];

export type VibecheckSeed = {
  text: string;
  theme: Theme;
  tags: Tag[];
  location_tag: LocationTag;
  activity_tag: ActivityTag;
  country: string;
  event_tag?: EventTag;
};

export const vibecheckSeeds: VibecheckSeed[] = [
  {
    text: 'Pizza in Fribourg doing bits',
    theme: 'funny',
    tags: ['iconic', 'food crawl', 'no crumbs'],
    location_tag: 'city',
    activity_tag: 'food crawl',
    country: 'Switzerland',
    event_tag: 'road trip',
  },
  {
    text: 'Boboli hills chose violence',
    theme: 'chaotic',
    tags: ['vibe shift', 'plot twist', 'hot take'],
    location_tag: 'park',
    activity_tag: 'hiking',
    country: 'Italy',
    event_tag: 'study abroad',
  },
  {
    text: 'POV: Your car is screaming uphill',
    theme: 'chaotic',
    tags: ['road trip', 'chaos energy', 'groupchat material'],
    location_tag: 'mountain',
    activity_tag: 'road trip',
    country: 'Switzerland',
    event_tag: 'grad trip',
  },
  {
    text: 'Capitoline steps: my final boss',
    theme: 'dramatic',
    tags: ['villain arc', 'emotional damage', 'plot twist'],
    location_tag: 'landmark',
    activity_tag: 'museum trip',
    country: 'Italy',
    event_tag: 'study abroad',
  },
  {
    text: 'My therapist said touch grass... touched clouds instead',
    theme: 'reflective',
    tags: ['touch grass', 'zen', 'deep'],
    location_tag: 'forest',
    activity_tag: 'hiking',
    country: 'any',
    event_tag: 'solo trip',
  },
  {
    text: 'Waterpark in JB unlocked childhood chaos',
    theme: 'nostalgic',
    tags: ['core memory', 'chaos energy', 'inner child'],
    location_tag: 'park',
    activity_tag: 'swimming',
    country: 'Malaysia',
    event_tag: 'family trip',
  },
  {
    text: 'Shouting into the Grand Canyon rn',
    theme: 'existential',
    tags: ['existential', 'deep', 'unfiltered'],
    location_tag: 'desert',
    activity_tag: 'hiking',
    country: 'United State of America',
    event_tag: 'gap year',
  },
  {
    text: 'Accidentally main charactered at a café',
    theme: 'aesthetic',
    tags: ['main character', 'daydream dump', 'iconic'],
    location_tag: 'city',
    activity_tag: 'people watching',
    country: 'any',
    event_tag: 'honeymoon',
  },
  {
    text: 'Gelato for dinner, no regrets',
    theme: 'unfiltered',
    tags: ['slay', 'no crumbs', 'tbh'],
    location_tag: 'city',
    activity_tag: 'food crawl',
    country: 'Italy',
    event_tag: 'just because',
  },
  {
    text: 'Sunset slapped me emotionally',
    theme: 'emotional',
    tags: ['crying', 'vibe shift', 'so real for that'],
    location_tag: 'lake',
    activity_tag: 'sunbathing',
    country: 'any',
    event_tag: 'couple trip',
  },
  {
    text: 'Paris café: villain arc unlocked',
    theme: 'dramatic',
    tags: ['villain arc', 'iconic', 'main character'],
    location_tag: 'city',
    activity_tag: 'people watching',
    country: 'France',
    event_tag: 'solo trip',
  },
  {
    text: 'Jewel Changi water vortex just therapized me',
    theme: 'existential',
    tags: ['airport delay', 'crying', 'unfiltered'],
    location_tag: 'building',
    activity_tag: 'airport delay',
    country: 'Singapore',
    event_tag: 'gap year',
  },
  {
    text: 'Tried to touch grass, met a yak',
    theme: 'silly',
    tags: ['touch grass', 'plot twist', 'chaos energy'],
    location_tag: 'mountain',
    activity_tag: 'hiking',
    country: 'Nepal',
    event_tag: 'retreat',
  },
  {
    text: 'Stole my personality from Kyoto streets',
    theme: 'aesthetic',
    tags: ['main character', 'deep', 'vibe shift'],
    location_tag: 'city',
    activity_tag: 'people watching',
    country: 'Japan',
    event_tag: 'study abroad',
  },
  {
    text: 'When in Rome… delulu edition',
    theme: 'funny',
    tags: ['delulu', 'soft launch', 'slay'],
    location_tag: 'landmark',
    activity_tag: 'museum trip',
    country: 'Italy',
    event_tag: 'honeymoon',
  },
  {
    text: 'Crying in the club (hostel kitchen)',
    theme: 'vulnerable',
    tags: ['crying', 'emotional damage', 'tbh'],
    location_tag: 'home',
    activity_tag: 'hostel chaos',
    country: 'any',
    event_tag: 'friendcation',
  },
  {
    text: 'Jungle Trail: survival of the slayest',
    theme: 'chaotic',
    tags: ['plot twist', 'chaos energy', 'groupchat material'],
    location_tag: 'jungle',
    activity_tag: 'hiking',
    country: 'Costa Rica',
    event_tag: 'group tour',
  },
  {
    text: 'Waffle in one hand, trauma in the other',
    theme: 'emotional',
    tags: ['food crawl', 'emotional damage', 'slay'],
    location_tag: 'market',
    activity_tag: 'food crawl',
    country: 'Belgium',
    event_tag: 'family trip',
  },
  {
    text: 'POV: me vs a Swiss cowbell',
    theme: 'silly',
    tags: ['chaos energy', 'hot take', 'so real for that'],
    location_tag: 'countryside',
    activity_tag: 'bike ride',
    country: 'Switzerland',
    event_tag: 'road trip',
  },
  {
    text: 'Sunrise said get wrecked emotionally 🌅',
    theme: 'emotional',
    tags: ['crying', 'vibe shift', 'iconic'],
    location_tag: 'mountain',
    activity_tag: 'sunrise mission',
    country: 'any',
    event_tag: 'couple trip',
  },
  {
    text: 'Back at the hostel, no thoughts just carbs',
    theme: 'unfiltered',
    tags: ['hostel chaos', 'food crawl', 'tbh'],
    location_tag: 'home',
    activity_tag: 'hostel chaos',
    country: 'any',
    event_tag: 'grad trip',
  },
  {
    text: 'Journaling in a tree like it’s 2013',
    theme: 'nostalgic',
    tags: ['inner child', 'core memory', 'crying'],
    location_tag: 'forest',
    activity_tag: 'camping',
    country: 'any',
    event_tag: 'retreat',
  },
  {
    text: 'Me and Lake Mjøsa got beef',
    theme: 'existential',
    tags: ['emotional damage', 'vibe shift', 'plot twist'],
    location_tag: 'lake',
    activity_tag: 'swimming',
    country: 'Norway',
    event_tag: 'solo trip',
  },
  {
    text: 'Climbed a volcano for the plot',
    theme: 'dramatic',
    tags: ['plot twist', 'main character', 'chaos energy'],
    location_tag: 'mountain',
    activity_tag: 'hiking',
    country: 'Indonesia',
    event_tag: 'bachelor trip',
  },
  {
    text: 'Pastel de nata said no more trauma',
    theme: 'funny',
    tags: ['food crawl', 'iconic', 'no crumbs'],
    location_tag: 'market',
    activity_tag: 'food crawl',
    country: 'any',
    event_tag: 'just because',
  },
  {
    text: 'This Hongdae club DJ read my trauma',
    theme: 'unfiltered',
    tags: ['clubbing', 'oversharing', 'emotional damage'],
    location_tag: 'city',
    activity_tag: 'clubbing',
    country: 'South Korea',
    event_tag: 'bachelor trip',
  },
  {
    text: 'Tacos al pastor hit harder than closure',
    theme: 'funny',
    tags: ['food crawl', 'no crumbs', 'emotional damage'],
    location_tag: 'market',
    activity_tag: 'food crawl',
    country: 'Mexico',
    event_tag: 'breakup trip',
  },
  {
    text: 'Northern lights said “you’re in love actually”',
    theme: 'romantic',
    tags: ['vibe shift', 'soft launch', 'dreamy'],
    location_tag: 'mountain',
    activity_tag: 'stargazing',
    country: 'Norway',
    event_tag: 'honeymoon',
  },
];

export default vibecheckSeeds;
