const LOCATION_TAGS = [
  'mountain',
  'beach',
  'forest',
  'city',
  'field',
  'park',
  'stadium',
  'desert',
  'island',
  'lake',
  'river',
  'jungle',
  'village',
  'countryside',
  'home',
  'hotel',
  'airbnb',
  'school',
  'market',
  'landmark',
  'building',
  'museum',
  'theme park',
  'water park',
  'mall',
  'cafe',
  'restaurant',
  'street',
  'any',
];

const ACTIVITY_TAGS = [
  'hiking',
  'camping',
  'swimming',
  'clubbing',
  'people watching',
  'sunbathing',
  'stargazing',
  'picnic',
  'train ride',
  'night market',
  'bike ride',
  'hostel chaos',
  'sunrise mission',
  'road trip',
  'museum trip',
  'karaoke night',
  'ferry ride',
  'cable car',
  'festival',
  'zipline',
  'waterfall dip',
  'food crawl',
  'bonfire',
  'airport delay',
  'tunnel walk',
  'photo dump',
  'paintball',
  'escape room',
  'photo booth',
  'cafe hopping',
  'fine dining',
  'shopping',
];

const LOCATION_TO_ACTIVITIES = {
  mountain: ['hiking', 'sunrise mission', 'camping', 'stargazing'],
  beach: ['swimming', 'sunbathing', 'food crawl', 'bonfire'],
  forest: ['hiking', 'camping', 'stargazing', 'zipline'],
  city: ['clubbing', 'food crawl', 'museum trip', 'karaoke night'],
  field: ['picnic', 'bike ride', 'sunrise mission', 'stargazing'],
  park: ['picnic', 'people watching', 'bike ride'],
  stadium: ['festival', 'karaoke night'],
  desert: ['sunrise mission', 'stargazing'],
  island: ['swimming', 'sunbathing', 'ferry ride'],
  lake: ['swimming', 'picnic', 'sunbathing', 'waterfall dip'],
  river: ['train ride', 'ferry ride'],
  jungle: ['hiking', 'zipline'],
  village: ['people watching', 'night market', 'food crawl'],
  countryside: ['bike ride', 'picnic', 'bonfire'],
  home: ['hostel chaos', 'karaoke night', 'bonfire'],
  school: ['people watching', 'hostel chaos'],
  market: ['night market', 'food crawl'],
  landmark: ['people watching', 'photo dump'],
  building: ['museum trip', 'people watching'],
  hotel: ['hostel chaos', 'sunbathing'],
  airbnb: ['bonfire', 'karaoke night'],
  any: [
    'people watching',
    'train ride',
    'road trip',
    'karaoke night',
    'hostel chaos',
    'festival',
  ],
};

module.exports = {
  LOCATION_TAGS,
  ACTIVITY_TAGS,
  LOCATION_TO_ACTIVITIES,
};
