const THEMES = [
  'funny',
  'reflective',
  'emotional',
  'nostalgic',
  'creative',
  'aesthetic',
  'chaotic',
  'vulnerable',
  'romantic',
  'existential',
  'silly',
  'dramatic',
  'zen',
  'dreamy',
  'unfiltered',
  'party',
];

const TAGS = [
  'delulu',
  'main character',
  'touch grass',
  'core memory',
  'hot take',
  'lowkey',
  'highkey',
  'crying',
  'vibe shift',
  'villain arc',
  'tbh',
  'iconic',
  'deep',
  'no crumbs',
  'slay',
  'unspoken rizz',
  'soft launch',
  'hard launch',
  'oversharing',
  'plot twist',
  'inner child',
  'emotional damage',
  '✨ energy',
  'so real for that',
  'chaos energy',
  'daydream dump',
  'groupchat material',
];

const EVENT_TAGS = [
  'grad trip',
  'road trip',
  'birthday',
  'honeymoon',
  'family trip',
  'solo trip',
  'couple trip',
  'friendcation',
  'school trip',
  'group tour',
  'study abroad',
  'bachelor trip',
  'retreat',
  'festival trip',
  'reunion trip',
  'gap year',
  'long distance meet',
  'breakup trip',
  'anniversary trip',
  'just because',
];

const EVENT_THEME_SUGGESTIONS = {
  'grad trip': ['funny', 'nostalgic', 'chaotic'],
  'road trip': ['creative', 'aesthetic', 'reflective'],
  birthday: ['funny', 'silly', 'existential', 'party'],
  honeymoon: ['romantic', 'dreamy', 'vulnerable'],
  'family trip': ['nostalgic', 'vulnerable', 'emotional'],
  'solo trip': ['existential', 'reflective', 'zen'],
  friendcation: ['funny', 'chaotic'],
  'school trip': ['funny', 'emotional', 'nostalgic'],
  'group tour': ['chaotic', 'creative', 'aesthetic'],
  'study abroad': ['nostalgic', 'creative', 'romantic'],
  'bachelor trip': ['chaotic', 'party', 'silly'],
  retreat: ['zen', 'reflective', 'dreamy'],
  'festival trip': ['party', 'aesthetic', 'chaotic'],
  'reunion trip': ['nostalgic', 'vulnerable', 'funny'],
  'gap year': ['existential', 'creative', 'unfiltered'],
  'long distance meet': ['romantic', 'emotional', 'chaotic'],
  'breakup trip': ['emotional', 'unfiltered', 'chaotic'],
  'anniversary trip': ['romantic', 'dreamy', 'reflective'],
  'just because': ['funny', 'creative'],
};

module.exports = {
  THEMES,
  TAGS,
  EVENT_TAGS,
  EVENT_THEME_SUGGESTIONS,
};
